Models/Project.cs
using Microsoft.AspNetCore.Http.HttpResults;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BugBurner.Models
{
    public class Project
    {
        private DateTime _created;
        private DateTime? _startDate;
        private DateTime? _endDate;

        //Primary Key
        public int Id { get; set; }

        //Foreign Key
        [Display(Name = "Company Name")]
        public int CompanyId { get; set; }

        [Required]
        [Display(Name = "Project Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} character long", MinimumLength = 2)]
        public string? Name { get; set; }

        [Required]
        [Display(Name = "Description")]
        [StringLength(5000, ErrorMessage = "The {0} must be at least {2} and max {1} character long", MinimumLength = 2)]
        public string? Description { get; set; }


        public DateTime Created
        {
            get { return _created; }
            set { _created = value.ToUniversalTime(); }
        }

        public DateTime? StartDate
        {
            get => _startDate;
            set
            {
                if (value.HasValue)
                {
                    _startDate = value.Value.ToUniversalTime();
                }
                else
                {
                    _startDate = null;
                }
            }
        }

        public DateTime? EndDate
        {
            get => _endDate;
            set
            {
                if (value.HasValue)
                {
                    _endDate = value.Value.ToUniversalTime();
                }
                else
                {
                    _endDate = null;
                }
            }
        }

        public int ProjectPriorityId { get; set; }

        [NotMapped]
        public IFormFile? ImageFormFile { get; set; }
        public byte[]? ImageFileData { get; set; }
        public string? ImageFileType { get; set; }
        public bool Archived { get; set; }

        //Navigational Properties
        public virtual Company? Company { get; set; }

        public virtual ProjectPriority? ProjectPriority { get; set; }

        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();

        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();
    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugBurner.Models.ViewModels
{
    public class AssignPMViewModel
    {
        public int ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public SelectList? PMList { get; set; }
        public string? PMId { get; set; }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BugBurner.Data;
using BugBurner.Models;
using BugBurner.Services.Interfaces;
using BugBurner.Extensions;
using BugBurner.Models.ViewModels;
using BugBurner.Models.Enums;
using Microsoft.AspNetCore.Authorization;

namespace BugBurner.Controllers
{
    [Authorize]
    public class ProjectsController : BTBaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IBTCompanyService _companyService;
        private readonly IBTFileService _btFileService;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;
        public ProjectsController(ApplicationDbContext context,IBTFileService bTFileService, IBTCompanyService bTCompanyService, IBTProjectService bTProjectService, IBTRolesService bTRolesService)
        {
            _context = context;
            _btFileService = bTFileService;
            _companyService = bTCompanyService;
            _projectService = bTProjectService;
            _rolesService = bTRolesService;

        }

        // GET: Projects
        
        public async Task<IActionResult> Index()
        {

            List<Project> projects = await _companyService.GetProjectsAsync(_companyId);
            return View(projects);
           
        }

        //Get: ALL Projects
        public async Task<IActionResult> ProjectHistories()
        {

            List<Project> projects = await _companyService.GetArchivedProjectsAsync(_companyId);
            return View(projects);
        }


        // GET: Projects/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        [Authorize(Roles ="Admin, ProjectManager")]
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin, ProjectManager")]
        public async Task<IActionResult> Create([Bind("Id,CompanyId,Name,Description,Created,StartDate,EndDate,ProjectPriorityId,ImageFormFile,Archived")] Project project)
        {
            ModelState.Remove("CompanyId");
            if (ModelState.IsValid)
            {
                //set the companyId
                int companyId = User.Identity!.GetCompanyId();

                //set image data if one has been chosen
                if (project.ImageFormFile != null)
                {
                    project.ImageFileData = await _btFileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                    project.ImageFileType = project.ImageFormFile.ContentType;
                }

                //set created date
                project.Created = DateTime.Now;

              await _projectService.AddProjectAsync(project);

                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Description,Created,StartDate,EndDate,ProjectPriorityId,ImageFileData,ImageFileType,ImageFormFile,Archived")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //set new image data if one has been chosen
                    if (project.ImageFormFile != null)
                    {
                        project.ImageFileData = await _btFileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                        project.ImageFileType = project.ImageFormFile.ContentType;
                    }

                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> ArchiveProject (int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            Project project = await _companyService.GetProjectDetailsAsync(id);


            if (project == null)
            {
                return NotFound();
            }

            await _projectService.ArchiveProjectAsync(project, project.Id);

			return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> UndoArchiveProject(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           Project project = await _projectService.GetProjectByIdAsync(id, _companyId);

            await _projectService.RestoreProjectAsync(project, _companyId);
            

            return RedirectToAction(nameof(Index));

        }

        private bool ProjectExists(int id)
        {
          return (_context.Projects?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpGet]
        public async Task<IActionResult> AssignPM(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if (project == null)
            {
                return NotFound();
            }

            // Get the list project managers
            IEnumerable<BTUser> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager),_companyId);
            BTUser? currentPM = await _projectService.GetProjectManagerAsync(id);
            AssignPMViewModel viewModel = new()
            {
                ProjectId = project.Id,
                ProjectName = project.Name,
                PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id),
                PMId = currentPM?.Id,
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignPM(AssignPMViewModel viewModel)
        {

            if(!string .IsNullOrEmpty(viewModel.PMId))
            {
                if(await _projectService.AddProjectManagerAsync(viewModel.PMId, viewModel.ProjectId))
                {
                    return RedirectToAction(nameof(Details), new {id = viewModel.ProjectId});
                }
                else
                {
                    ModelState.AddModelError("PMId", "Error assigning a PM.");
                }

            }

            ModelState.AddModelError("PMId", "No Project Manager Chosen. Please select a PM.");
            IEnumerable<BTUser> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);
            BTUser? currentPM = await _projectService.GetProjectManagerAsync(viewModel.ProjectId);
            viewModel.PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AssignProjectMembers(int? id)
        {
            if(id == null)
            {

Views/Projects/AssignPM.cshtml
@model AssignPMViewModel 
@{
    ViewData["Title"] = "Assign Project Manager";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="ProjectId" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <span asp-validation-for="PMId" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                @*<a asp-action="Details" asp-route-id="@Model.ProjectId" class="btn btn-secondary">Cancel</a>*@
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/AssignProjectMembers.cshtml
@model ProjectMembersViewModel;
@{
    ViewData["Title"] = "Assign Project Members";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project!.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.UserList" asp-for="SelectedMembers" class="form-control" multiple required>
                </select>
                <span asp-validation-for="SelectedMembers" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                <a asp-action="Details" asp-route-id="@Model.Project!.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/Create.cshtml
@model BugBurner.Models.Project
@inject IBTFileService _BTFileService;

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Create</h1>

<h4 class="text-center">Project</h4>
<hr />
<div class="row justify-content-center mb-3">
    <div class="col-md-6">
        <form asp-action="Create" asp-controller="Projects" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ImageFormFile" class="control-label">Project Image</label>
                <img class="img-fluid border rounded-3 mb-2" style="max-height: 350px;" src="@_BTFileService.ConvertByteArrayToFile(Model?.ImageFileData!,Model?.ImageFileType!,DefaultImage.ProjectImage)" id="ProjectImage">
                <input asp-for="ImageFormFile" type="file" class="form-control mt-3 pt-2" accept=".png,.jpg,.jpeg,.gif"
                       onchange="document.getElementById('blogImage').src = window.URL.createObjectURL(this.files[0])" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPriorityId" class="control-label"></label>
                <select asp-for="ProjectPriorityId" class ="form-control" asp-items="ViewBag.ProjectPriorityId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Archived" /> @Html.DisplayNameFor(model => model.Archived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Delete.cshtml
@model BugBurner.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Details.cshtml
@model BugBurner.Models.Project
@inject IBTFileService _BTFileService;
@inject IBTProjectService _ProjectService;
@inject UserManager<BTUser> _UserManager;
@inject IBTNotificationService _notificationService;
@inject IBTCompanyService _companyService;
@inject IBTTicketService _ticketService;
@{
    ViewData["Title"] = "Details";
    BTUser? bTUser = await _UserManager.GetUserAsync(User);
    int companyId = bTUser.CompanyId;

    BTUser? Pm = await _ProjectService.GetProjectManagerAsync(Model.Id);

    List<BTUser> developers = await _ProjectService.GetProjectMembersByRoleAsync(Model.Id, "Developer", companyId);
}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->
<div class="row pt-3 pb-3">
    <div class="col-md-8">
        <div class="card ms-3">
            <div class="card-body task-detail">
                <div class="d-flex mb-3">
                    <div class="flex-grow-1">
                        @if (Pm != null)
                        {
                            <h4 class="media-heading mt-0">@Pm.FullName</h4>
                        }
                        else
                        {
                            <h4 class="media-heading mt-0">No Project Manager</h4>
                        }
                        <span class="badge bg-danger">@Model.ProjectPriority!.Name</span>
                    </div>
                </div>
                @*title*@
                <h4>@Model.Name</h4>
                @*description*@
                <p class="text-muted">
                    @Model.Description
                </p>

                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-6">
                        <h5 class="font-600 m-b-5">Start Date</h5>
                        <p> @Model.Created</p>
                    </div>

                    <div class="col-lg-6">
                        <h5 class="font-600 m-b-5">Due Date</h5>
                        <p> @Model.EndDate</p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <hr />
            </div>
        </div>
        @*Tickets Table*@
        <h4>Tickets</h4>
        <hr />
       <div class="card">
                <div class="card-body">
                    @*tickets Table*@
                    <h4 class="header-title mt-0 mb-3">Latest Tickets</h4>

                    <div class="table-responsive">
                        <table class="table table-hover mb-0" id="ticketTable">

                            <thead>
                                <tr>
                                    <th>Project Name</th>
                                    <th>Start Date</th>
                                    <th>Status</th>
                                    <th>Developer</th>
                                </tr>
                            </thead>
                            <tbody>
                                    @foreach (Ticket ticket in Model.Tickets)
                                    {
                                        <tr>
                                            <td>@ticket.Title</td>
                                            <td>@ticket.Created</td>
                                            @if (ticket.TicketPriority?.Name == "High")
                                            {
                                                <td><span class="badge bg-warning">@ticket.TicketPriority!.Name</span></td>

                                            }
                                            else if (ticket.TicketPriority?.Name == "Urgent")
                                            {
                                                <td><span class="badge bg-danger">@ticket.TicketPriority!.Name</span></td>

                                            }
                                            else if (ticket.TicketPriority?.Name == "Low")
                                            {
                                                <td><span class="badge bg-success">@ticket.TicketPriority!.Name</span></td>
                                            }
                                            else if (ticket.TicketPriority?.Name == "Medium")
                                            {
                                                <td><span class="badge bg-pink">@ticket.TicketPriority!.Name</span></td>
                                            }

                                            @if (ticket.DeveloperUser != null)
                                            {
                                                <td>@ticket.DeveloperUser!.FullName</td>
                                            }
                                            else
                                            {
                                                <td>Unassigned</td>
                                            }
                                        </tr>
                                    }                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>

    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5>Project Members</h5>
                <hr />
                <div class="assign-team mt-3">
                    @if (User.IsInRole("ProjectManager") || User.IsInRole("Admin"))
                    {
                        <a class="btn btn-sm btn-success" asp-action="AssignProjectMembers" asp-controller="Projects" asp-route-id="@Model.Id">Manage Members</a>
                    }
                    <div class="">
                        @if (Pm != null)
                        {
                            <div class="card">
                                <div class="card-body widget-user">
                                    <div class="d-flex align-items-center">
                                        <div class="flex-grow-1 overflow-hidden">
                                            <h5 class="mt-0 mb-1">@Pm.FullName</h5>
                                            <p class="text-muted mb-2 font-13 text-truncate">@Pm.Email</p>
                                            <small class="text-primary"><b>Project Manager</b></small><br>
                                            @if (User.IsInRole("ProjectManager") || User.IsInRole("Admin"))
                                            {
                                                <a class="btn btn-sm btn-primary" asp-action="AssignPm" asp-controller="Projects" asp-route-id="@Model.Id">Assign Pm</a>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        @foreach (BTUser member in developers)
                        {

                            <div class="card">
                                <div class="card-body widget-user">
                                    <div class="d-flex align-items-center">
                                        <div class="flex-grow-1 overflow-hidden">
                                            <h5 class="mt-0 mb-1">@member.FullName</h5>
                                            <p class="text-muted mb-2 font-13 text-truncate">@member.Email</p>
                                            <small class="text-success"><b>Developer</b></small><br>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

    </div><!-- end col -->
    <!-- end row -->
</div>
<!-- end row -->
<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->
@section Scripts{

    <script>
        $('#ticketTable').DataTable();
    </script>
    @* Morris Donut Chart *@
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>


}